# Generated by Django 5.0.4 on 2024-06-03 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Escriba el título de la tarea', max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Indique una breve descripción de la tarea', null=True, verbose_name='Descripción')),
                ('prioridad', models.IntegerField(default=1, help_text='Indique la prioridad de la tarea', verbose_name='Prioridad')),
                ('fecha_inicial', models.DateField(default=datetime.date.today, verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tbl_tarea',
                'ordering': ('id', 'titulo'),
            },
        ),
    ]
