# Generated by Django 5.0.4 on 2024-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.PositiveIntegerField(default=1, help_text='Indique la prioridad de la tarea', verbose_name='Prioridad'),
        ),
    ]
